name: Test Actions Docker

on: [pull_request]
# on: [push]

jobs:
  run-my-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use my Action
        id: hello
        uses: ./.github/actions/hello-docker
        with:
          who-to-say-hello: "Pepe Ch."
      - name: Log Greeting output
        run: echo "Pepe Action Time ${{ steps.hello.outputs.time }}"
