name: WebSandUnitTest

on:
  push:
    branches:
      - master
jobs:
  run-websand-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r websand/requirements.txt
      - name: Run Web Sand Unit tests
        run: |
          python -m unittest discover -s websand/tests -p "*_unittest.py" -v